**Module :** CCS4340 - Machine Learning

**Acitivity :** Lab 4 - Decision Tree

**Submitted by :** CIT-23-02-0162 | Jayani Sashikala

**Date of Submission :** 2026/01/10

# 🔵 **Introduction**
This mini project focuses on predicting student academic performance using a Decision Tree classifier. The goal is to identify whether a student will Pass or Fail based on academic and behavioral factors. Such a system helps educational institutions identify at risk students early and provide academic support.

# 🔵 **Dataset Description**
The dataset contains student academic and study related attributes.

Features:

*   **Attendance_Percentage** - Student attendance in percentage
*   **Midterm_Marks** - Marks obtained in midterm exam
*   **Assignment_Score** - Assignment marks
*   **Study_Hours_Per_Week** - Average weekly study hours
*   **Previous_GPA** - GPA from previous semester

Target Variable:

*   Pass
*   Fail

# 🔵 **Process of the Lab Task**

## Srep 1 - Import Required Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.metrics import accuracy_score, confusion_matrix

## Step 2 - Load the Dataset

In [25]:
# Read the CSV file
df = pd.read_csv("Student_Performance.csv")
df

,Attendance_Percentage,Midterm_Marks,Assignment_Score,Study_Hours_Per_Week,Previous_GPA,Final_Result
0,49,12,73,36,3.10,Pass
1,55,35,10,37,3.06,Fail
2,96,98,1,31,3.24,Pass
3,44,82,17,13,2.29,Fail
4,88,90,59,32,3.98,Pass
...,...,...,...,...,...,...
195,69,24,51,29,3.48,Pass
196,63,26,17,27,2.66,Fail
197,83,67,99,28,3.87,Pass
198,79,48,86,25,2.43,Pass
199,70,29,14,21,2.94,Fail

## Step 3 - Dataset Exploration

The dataset was loaded into a pandas DataFrame and basic exploration was performed.

*   Checked dataset shape
*   Checked for missing values
*   Verified data types and dataset information

This step helped to understand the structure and quality of the dataset.

In [6]:
# Dataset shape
print("\nDataset shape:")
print(df.shape)

# Missing value
print("\nMissing values:")
print(df.isnull().sum())

# Dataset Information
print("\nDataset information:")
print(df.info())

Dataset shape:
(200, 6)

Missing values:
Attendance_Percentage    0
Midterm_Marks            0
Assignment_Score         0
Study_Hours_Per_Week     0
Previous_GPA             0
Final_Result             0
dtype: int64

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Attendance_Percentage  200 non-null    int64
 1   Midterm_Marks          200 non-null    int64
 2   Assignment_Score       200 non-null    int64
 3   Study_Hours_Per_Week   200 non-null    int64
 4   Previous_GPA           200 non-null    float64
 5   Final_Result           200 non-null    object
dtypes: float64(1), int64(4), object(1)
memory usage: 9.5+ KB
None

## Step 4 - Basic Data Analysis

Basic statistical analysis was performed to understand the distribution of values.


*   Count,mean, standard deviation, minimum, and maximum values were examined
*   This analysis showed how attendance, marks, and GPA affect student performance

In [5]:
# Statistical summary
df.describe()

,Attendance_Percentage,Midterm_Marks,Assignment_Score,Study_Hours_Per_Week,Previous_GPA
count,200.000000,200.000000,200.000000,200.000000,200.000000
mean,70.235000,50.295000,48.670000,20.990000,2.945000
std,18.045999,29.719086,29.738409,10.653044,0.604926
min,40.000000,0.000000,0.000000,1.000000,2.010000
25%,54.750000,24.000000,24.000000,12.000000,2.437500
50%,72.000000,49.000000,47.500000,21.000000,2.905000
75%,86.000000,77.000000,74.250000,30.000000,3.425000
max,99.000000,99.000000,99.000000,39.000000,4.000000

## Step 5 - Encode the Target Variable

The target variable Final_Result was categorical (Pass / Fail).

It was encoded into numerical form so that the Decision Tree model could process it.
*   Pass - 1
*   Fail - 0

In [8]:
# Encode target variable
df['Final_Result'] = df['Final_Result'].map({'Pass': 1, 'Fail': 0})

df.head()

,Attendance_Percentage,Midterm_Marks,Assignment_Score,Study_Hours_Per_Week,Previous_GPA,Final_Result
0,49,12,73,36,3.10,1
1,55,35,10,37,3.06,0
2,96,98,1,31,3.24,1
3,44,82,17,13,2.29,0
4,88,90,59,32,3.98,1

## Step 6 - Define Features and Target

**X** contains the input features (Attendance_Percentage, Midterm_Marks, Assignment_Score, Study_Hours_Per_Week, and Previous_GPA) that are used to predict student performance.

**y** contains the target variable (Final_Result), which represents whether the student passed or failed.

In [10]:
x = df[["Attendance_Percentage", "Midterm_Marks", "Assignment_Score", "Study_Hours_Per_Week", "Previous_GPA"]]
y = df["Final_Result"]

## Step 7 - Train-Test Split

The dataset was split into,

*   **Training set** – used to train the model
*   **Testing set** – used to evaluate performance

This ensures that the model is tested on unseen data.

In [11]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42)

## Step 8 - Train the Decision Tree Classifier

A Decision Tree Classifier was used to train the model.

*   The model learned decision rules from the training data
*   Features such as attendance, marks, and GPA were used to predict the final result

In [12]:
dt_model = DecisionTreeClassifier(max_depth=4, random_state=42)

In [13]:
dt_model.fit(x_train, y_train)

DecisionTreeClassifier(max_depth=4, random_state=42)

## Step 9 - Make Predictions


*   y_pred stores the predicted results generated by the trained Decision Tree model using the test data.
*   The comparison DataFrame displays the actual values and predicted values side by side to easily compare model performance.

In [14]:
y_pred = dt_model.predict(x_test)

In [17]:
comparison = pd.DataFrame({"Actual": y_test.values, "Predicted": y_pred})

In [18]:
comparison.head()

   Actual  Predicted
0       0          0
1       1          1
2       0          1
3       1          0
4       0          0

## Step 10 - Evaluate the Model

The trained model was evaluated using accuracy.
*   Accuracy measures how correctly the model predicts Pass or Fail
*   A good accuracy value indicates that the model performs well on test data

In [20]:
accuracy = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)

In [22]:
print("Model Accuracy:", accuracy)
print("Confusion Matrix:\n", cm)

Model Accuracy: 0.76
Confusion Matrix:
 [[ 9  6]
 [ 6 29]]

## Step 11 - Overfitting Control

Overfitting occurs when the tree becomes too deep and learns noise from training data.

Underfitting occurs when the tree is too shallow and fails to capture important patterns.

Tree complexity can be controlled using parameters such as,

*   max_depth
*   min_samples_split
*   min_samples_leaf

In [23]:
# Decision Tree with controlled depth
dt_limited = DecisionTreeClassifier(
    max_depth=3,
    min_samples_split=2,
    random_state=42
)

dt_limited.fit(x_train, y_train)

y_pred_limited = dt_limited.predict(x_test)

accuracy_limited = accuracy_score(y_test, y_pred_limited)

print("Accuracy with controlled tree:", accuracy_limited)

Accuracy with controlled tree: 0.66

# 🔵 **Conclusion**
In this mini project, a Decision Tree classifier was successfully used to predict student performance. The model demonstrated how academic and behavioral factors influence pass or fail outcomes. Decision Trees are easy to interpret and suitable for educational data, but proper tuning is required to avoid overfitting.